### ISSUE TITLE
redirectDocument doesn't work

### ISSUE THREAD

**Issue by Spheerys** [marcushouse/JsonFormBuilder#15]
Hi,

I have followed the tutorial to make my form, and everything works except the redirect option (after validation).
The mail is sent but the form page is reloaded in place of being redirected to the "thank you" page.

**Comment by Spheerys** [comment]
On the modx log, I have this : 
```
[2016-09-12 19:19:45] (ERROR @ /home/Hedy/web/site.fr/public_html/core/model/modx/modresponse.class.php : 208) Attempted to redirect to an empty URL.
```
But the doc id I have set is existing, and the resource published.
If I set a "small" id (such as 1 or 22), the redirection is working.
But with my 209 id is not working... I'm digging further...

**Comment by Spheerys** [comment]
I have found a "dirty" work around : I used an old unused resource with a low id and it's work now.
It's like if the redirect page id is higher than the form resource id, it's not working... very strange...

**Comment by marcushouse** [comment]
Thanks for debugging. I suspect something was odd with that resource (in the past I've had issues with resources that appear to be published but then don't actually work due to an obscure issue with an alias or something).
