### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by craigphiz** [marcushouse/JsonFormBuilder#7]
Interested in using this instead of FormIt (which I'm having checkbox difficulties with) but the documentation is offline. 

Server at http://modxrevo.datawebnet.com.au/jsonformbuilder reports Bandwidth Exceeded.

Does anyone have the docs they could upload to this repo?

Thanks!

**Comment by marcushouse** [comment]
Sorry about that. It is all back up now.
